language: go
go:
- 1.13
script:
- go get -u
- GOOS=linux go build -o vault-wrapper
sudo: false
before_deploy:
- echo "Deploying $TRAVIS_TAG to GitHub releases"
- tar czf vault-wrapper-linux.tar.gz vault-wrapper
deploy:
  provider: releases
  api_key:
    secure: mflWu4zISKB1qbIzO0cfwAiEaW/aK5/BAjs0LuZ5/OsTHj5KytzIy7UIybMZkyMvaWjDvZQCgxhW4g/tS8hlYpU7ri2E9hKx+3SFiyjU4ayCSKtSINjA/EI+07ZrYN7OO7RmrnvmGzW0xF46Aqhud9cluOEU3F3zGz1CgR/5JxUSlJpZY+RHUhOFmaxbj2YrXRL0A7D/X5NWrgOB2dULgXW9Qgx8hyOO15jW0LEhqTJ7fsP6i80KO37gFsMXZlhPYAZMRE7dxuO29yuV4h8rszLXIqw5GVfebJ5nNi3uPuA+DVtGgVvRfygjWj79vLOIzfyg1WJrz7WdVb5ikxq4jh9TynM7JkBqxQJfDx0+RkKSO/22k65KoJBo0ucS6Y2tgNn+jrl3JdSzjkFmwMn9Hc3FPkDkyO/9T7dUveMx//Xzm1oW1Sc+BzhB/jd99ktfS4feJ+QQg7QcCpJY7kxnhU3PSnEUqMwgvhP/eS4t5Kr48bf8XKmftJEUYwoIEV2OAsbngGvYSlpmd0OvXidYHOHRZY3CdwavbCNOBJy83ppLAGBnjMiNMh3zanEIWbMvd9+d3FfzE4PrQDVrwIPkqNugMyPq/9Vg+uQnKZ/A0s6DKKZ5QbDKc9rmQd3tlUG55yY7S0rJqcJUbtH+8bLvaU17E7nsj506iZaGMUg763E=
  file: vault-wrapper-linux.tar.gz
  on:
    repo: tionebsalocin/vault-wrapper
    tags: true
  skip_cleanup: 'true'
